-- CreateEnum
CREATE TYPE "Role" AS ENUM ('ADMIN', 'USER', 'TECHSUPPORT');

-- CreateEnum
CREATE TYPE "Award" AS ENUM ('HALF_YEAR_ON_SITE', 'ONE_YEAR_ON_SITE', 'TWO_YEARS_ON_SITE', 'THREE_YEARS_ON_SITE', 'FOUR_YEARS_ON_SITE', 'FIVE_YEARS_ON_SITE', 'MESSANGER', 'RECIEVER', 'PUBLIC1', 'PUBLIC2', 'PUBLIC3', 'PUBLIC4', 'PUBLIC5');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "awards" "Award"[],
ADD COLUMN     "role" "Role" NOT NULL DEFAULT E'USER';

-- CreateTable
CREATE TABLE "Visit" (
    "id" SERIAL NOT NULL,
    "visitAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ip" TEXT NOT NULL,

    CONSTRAINT "Visit_pkey" PRIMARY KEY ("id")
);
